### ISSUE TITLE
Goal: Deleting a row

### ISSUE THREAD

**Issue by ecumene** [Valderhide/inventory#36]

**Comment by Valderhide** [comment]
Will refresh table on first button click. but not on subsequent button clicks.

const removeItem = () => {
    let properties = JSON.parse(localStorage.getItem('properties'));
    let newProperties = localStorage.setItem('properties', JSON.stringify(properties))
    
    properties.splice(properties, 1)
      localStorage.setItem('properties', JSON.stringify(properties))
      setData(newProperties);
    
  }

**Comment by ecumene** [comment]
You'll need to use 

```
properties.filter((item) => item.id !== "Third")
```
