### ISSUE TITLE
GOAL: Get search working!

### ISSUE THREAD

**Issue by ecumene** [Valderhide/inventory#57]
- [x] Replace search row with text fields
- [x] Whenever you change one it should call a function with the new values
- [x] Use the new values to filter data into a new state variable
- [x] Once that's filtered, render only the filtered results

**Comment by Valderhide** [comment]
all above completed. Just not spread across multiple columns of table

**Comment by ecumene** [comment]
![Untitled-2022-01-31-1121](https://user-images.githubusercontent.com/6249465/163416860-3b2838a1-991b-4835-90a9-371014e63053.png)

**Comment by ecumene** [comment]
![Untitled-2022-01-31-1121](https://user-images.githubusercontent.com/6249465/163417514-b64574ec-4ff1-4db6-934c-469bc1d25b87.svg)
