### ISSUE TITLE
Change all files to be the correct cases

### ISSUE THREAD

**Issue by ecumene** [Valderhide/inventory#68]

**Comment by Valderhide** [comment]
getting 
fatal: not under version control, source=src/pages/homepage.js, destination=src/pages/Homepage.js
when attempting to change filename with git mv

**Comment by ecumene** [comment]
Try renaming them in Github instead

**Comment by ecumene** [comment]
Also:
 - [ ] `Print Shopping List.js` -> `ShopppingList.js`
